# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 21:19
from __future__ import unicode_literals

import apps.login_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, validators=[apps.login_app.models.validateword]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, validators=[apps.login_app.models.validateword]),
        ),
    ]
